[theme]
base = "light"
primaryColor = "#FFD633"
backgroundColor = "#FAF9F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#24262D"
linkColor = "#735800"
borderColor = "#DCDAD2"
dataframeBorderColor = "#DCDAD2"
dataframeHeaderBackgroundColor = "#EEECE4"
showWidgetBorder = true
baseRadius = "0.65rem"
buttonRadius = "0.5rem"
blueColor = "#276286"
blueBackgroundColor = "#EAF2F7"
blueTextColor = "#234F6B"
greenColor = "#287452"
greenBackgroundColor = "#EAF4EE"
greenTextColor = "#245D42"
yellowColor = "#987000"
yellowBackgroundColor = "#FFF4CF"
yellowTextColor = "#6E5100"
redColor = "#B13E3E"
redBackgroundColor = "#FBECEC"
redTextColor = "#922F2F"
chartCategoricalColors = ["#B58A00", "#276286", "#287452", "#7D609B"]

[theme.sidebar]
primaryColor = "#FFD633"
backgroundColor = "#24262D"
secondaryBackgroundColor = "#30333C"
textColor = "#F5F4EF"
linkColor = "#FFE477"
borderColor = "#545761"
yellowBackgroundColor = "#393321"
yellowTextColor = "#F8DB72"
